listing:
  path:     /listing
  defaults: { _controller: AppBundle:Default:listing }

scenario_ajax_get_products:
  path:     /ajax/get-products
  defaults: { _controller: AppBundle:Scenario:ajaxGetProducts }
  condition: "request.isXmlHttpRequest()"

scenario_ajax_check_for_refresh:
  path:     /ajax/check-for-refresh
  defaults: { _controller: AppBundle:Scenario:ajaxCheckForRefresh }
  condition: "request.isXmlHttpRequest()"

scenario_all:
  path:     /all
  defaults: { _controller: AppBundle:Scenario:all }

scenario_person:
  path:     /person
  defaults: { _controller: AppBundle:Scenario:person }

scenario_camera:
  path:     /camera
  defaults: { _controller: AppBundle:Scenario:camera }


settings_index:
  path:     /settings
  defaults: { _controller: AppBundle:Settings:index }


emulator_index:
  path:     /emulator
  defaults: { _controller: AppBundle:Emulator:index }

showroom_info:
  path:     /showroom/info
  defaults: { _controller: AppBundle:Emulator:info }
