scenario_listing:
  path:     /listing
  defaults: { _controller: AppBundle:Scenario:listing }

scenario_all:
  path:     /all
  defaults: { _controller: AppBundle:Scenario:all }

scenario_person:
  path:     /person
  defaults: { _controller: AppBundle:Scenario:person }

scenario_camera:
  path:     /camera
  defaults: { _controller: AppBundle:Scenario:camera }


settings_index:
  path:     /settings
  defaults: { _controller: AppBundle:Settings:index }
